export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS courses (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('teacher', 'student')),
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS class_members (
    class_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('teacher', 'student')),
    joined_at TEXT NOT NULL,
    PRIMARY KEY (class_id, user_id),
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    action TEXT NOT NULL,
    object_type TEXT NOT NULL,
    object_id TEXT,
    detail TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS classes (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    course_name TEXT NOT NULL,
    term TEXT NOT NULL,
    join_code TEXT NOT NULL UNIQUE,
    teacher_name TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS course_classes (
    course_id TEXT NOT NULL,
    class_id TEXT NOT NULL,
    PRIMARY KEY (course_id, class_id),
    FOREIGN KEY (course_id) REFERENCES courses(id),
    FOREIGN KEY (class_id) REFERENCES classes(id)
  )`,
  `CREATE TABLE IF NOT EXISTS chapters (
    id TEXT PRIMARY KEY,
    class_id TEXT NOT NULL,
    name TEXT NOT NULL,
    files_count INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'draft',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    FOREIGN KEY (class_id) REFERENCES classes(id)
  )`,
  `CREATE TABLE IF NOT EXISTS materials (
    id TEXT PRIMARY KEY,
    chapter_id TEXT NOT NULL,
    name TEXT NOT NULL,
    file_type TEXT NOT NULL,
    size_label TEXT NOT NULL,
    download_url TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (chapter_id) REFERENCES chapters(id)
  )`,
  `CREATE TABLE IF NOT EXISTS students (
    id TEXT PRIMARY KEY,
    class_id TEXT NOT NULL,
    name TEXT NOT NULL,
    initials TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (class_id) REFERENCES classes(id)
  )`,
  `CREATE TABLE IF NOT EXISTS assignments (
    id TEXT PRIMARY KEY,
    class_id TEXT NOT NULL,
    chapter_id TEXT,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    deadline TEXT NOT NULL DEFAULT '未设置',
    status TEXT NOT NULL DEFAULT 'draft',
    created_at TEXT NOT NULL,
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (chapter_id) REFERENCES chapters(id)
  )`,
  `CREATE TABLE IF NOT EXISTS learning_tasks (
    id TEXT PRIMARY KEY,
    class_id TEXT NOT NULL,
    chapter_id TEXT,
    task_type TEXT NOT NULL CHECK (task_type IN ('preview', 'material', 'assignment', 'review')),
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    start_at TEXT,
    due_at TEXT,
    status TEXT NOT NULL DEFAULT 'published',
    created_at TEXT NOT NULL,
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (chapter_id) REFERENCES chapters(id)
  )`,
  `CREATE TABLE IF NOT EXISTS task_records (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    student_id TEXT NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'completed',
    completed_at TEXT,
    updated_at TEXT NOT NULL,
    UNIQUE (task_id, student_id),
    FOREIGN KEY (task_id) REFERENCES learning_tasks(id),
    FOREIGN KEY (student_id) REFERENCES students(id)
  )`,
  `CREATE TABLE IF NOT EXISTS lesson_sessions (
    id TEXT PRIMARY KEY,
    class_id TEXT NOT NULL,
    chapter_id TEXT,
    teacher_user_id TEXT,
    start_time TEXT NOT NULL,
    end_time TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (chapter_id) REFERENCES chapters(id),
    FOREIGN KEY (teacher_user_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS activities (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    activity_type TEXT NOT NULL CHECK (activity_type IN ('choice', 'poll', 'short_answer')),
    prompt TEXT NOT NULL,
    options TEXT NOT NULL DEFAULT '[]',
    status TEXT NOT NULL DEFAULT 'published',
    created_at TEXT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES lesson_sessions(id)
  )`,
  `CREATE TABLE IF NOT EXISTS activity_responses (
    id TEXT PRIMARY KEY,
    activity_id TEXT NOT NULL,
    student_id TEXT NOT NULL,
    answer TEXT NOT NULL DEFAULT '',
    submitted_at TEXT NOT NULL,
    UNIQUE (activity_id, student_id),
    FOREIGN KEY (activity_id) REFERENCES activities(id),
    FOREIGN KEY (student_id) REFERENCES students(id)
  )`,
  `CREATE TABLE IF NOT EXISTS learning_events (
    id TEXT PRIMARY KEY,
    class_id TEXT NOT NULL,
    student_id TEXT,
    session_id TEXT,
    event_type TEXT NOT NULL,
    object_type TEXT NOT NULL,
    object_id TEXT,
    payload TEXT NOT NULL DEFAULT '{}',
    occurred_at TEXT NOT NULL,
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (student_id) REFERENCES students(id),
    FOREIGN KEY (session_id) REFERENCES lesson_sessions(id)
  )`,
  `CREATE TABLE IF NOT EXISTS student_insights (
    id TEXT PRIMARY KEY,
    class_id TEXT NOT NULL,
    student_id TEXT NOT NULL,
    completion_rate REAL NOT NULL DEFAULT 0,
    assignment_rate REAL NOT NULL DEFAULT 0,
    activity_rate REAL NOT NULL DEFAULT 0,
    average_score REAL,
    attention_reason TEXT NOT NULL DEFAULT '',
    calculated_at TEXT NOT NULL,
    UNIQUE (class_id, student_id),
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (student_id) REFERENCES students(id)
  )`,
  `CREATE TABLE IF NOT EXISTS class_insights (
    id TEXT PRIMARY KEY,
    class_id TEXT NOT NULL UNIQUE,
    preview_completion_rate REAL NOT NULL DEFAULT 0,
    assignment_completion_rate REAL NOT NULL DEFAULT 0,
    activity_participation_rate REAL NOT NULL DEFAULT 0,
    average_score REAL,
    score_distribution TEXT NOT NULL DEFAULT '{}',
    calculated_at TEXT NOT NULL,
    FOREIGN KEY (class_id) REFERENCES classes(id)
  )`,
  `CREATE TABLE IF NOT EXISTS submissions (
    id TEXT PRIMARY KEY,
    assignment_id TEXT NOT NULL,
    student_id TEXT NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    attachment_name TEXT,
    status TEXT NOT NULL DEFAULT 'submitted',
    score TEXT,
    feedback TEXT,
    submitted_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (assignment_id, student_id),
    FOREIGN KEY (assignment_id) REFERENCES assignments(id),
    FOREIGN KEY (student_id) REFERENCES students(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_chapters_class_id ON chapters(class_id)`,
  `CREATE INDEX IF NOT EXISTS idx_materials_chapter_id ON materials(chapter_id)`,
  `CREATE INDEX IF NOT EXISTS idx_assignments_class_id ON assignments(class_id)`,
  `CREATE INDEX IF NOT EXISTS idx_learning_tasks_class_id ON learning_tasks(class_id)`,
  `CREATE INDEX IF NOT EXISTS idx_task_records_task_id ON task_records(task_id)`,
  `CREATE INDEX IF NOT EXISTS idx_lesson_sessions_class_id ON lesson_sessions(class_id)`,
  `CREATE INDEX IF NOT EXISTS idx_activities_session_id ON activities(session_id)`,
  `CREATE INDEX IF NOT EXISTS idx_activity_responses_activity_id ON activity_responses(activity_id)`,
  `CREATE INDEX IF NOT EXISTS idx_learning_events_class_time ON learning_events(class_id, occurred_at)`,
  `CREATE INDEX IF NOT EXISTS idx_learning_events_student ON learning_events(student_id, occurred_at)`,
  `CREATE INDEX IF NOT EXISTS idx_student_insights_class ON student_insights(class_id)`,
  `CREATE INDEX IF NOT EXISTS idx_submissions_assignment_id ON submissions(assignment_id)`,
  `CREATE INDEX IF NOT EXISTS idx_class_members_user_id ON class_members(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at)`,
];
